### ISSUE TITLE
release current master version

### ISSUE THREAD

**Issue by pjvds** [open-pomodoro/openpomodoro-cli#12]
You recently turned openpromodoro-cli into a Go module. It would help significatly if you release the current master. This would help packing the release for several packaging systems.

Just tagging it would be sufficient.

**Comment by justincampbell** [comment]
Thanks @pjvds! I've tagged and pushed v0.2.0.

The installation instructions right now are to `go install github.com/open-pomodoro/openpomodoro-cli/cmd/pomodoro`, so that the command installs as `pomodoro` instead of `openpomodoro-cli`. However, I'm not sure now with the versioned root module if I need to do anything else to get this working properly, since the subcommand is not versioned? It may be moot as I plan to move the project to GoReleaser + GitHub Actions instead of Travis CI soon.

**Comment by justincampbell** [comment]
Btw I'll also work on tagging and pushing the SDK code.

**Comment by pjvds** [comment]
@justincampbell thanks! I've added open-pomodoro to the [AUR](https://aur.archlinux.org/packages/openpomodoro/).

Keep up the great work!
